### ISSUE TITLE
Allow folder properties to be visible at child SCM section

### ISSUE THREAD

**Issue by sankirthan** [mig82/folder-properties-plugin#2]
This way SCM url could be parameterized

**Comment by mig82** [comment]
Hi @sankirthan, 

Could you please point to another plugin that works like this -and maybe even provide a screenshot- so I can better understand what you're looking for and see whether it's a quick fix or not?

Thank you.

**Comment by sankirthan** [comment]
Hi Miguel,
I haven't seen any myself.  Just want some properties at the folder level
that can be referred from child jobs.  Ability to support scm url at a
folder level would be tricky.

I ended up just repeating the properties.

Maybe this can all be done if using pipeline scripts.  I haven't explored
that option.

Regards
Sankirthan

**Comment by StefanHirche** [comment]
Maybe it is enough to override runPreCheckout() to return true. It looks like then the setUp runs before SCM code.

**Comment by mig82** [comment]
I'm closing this issue in favour of this [PR #5 in the jenkinsci repo](https://github.com/jenkinsci/folder-properties-plugin/pull/5).
