### ISSUE TITLE
Allow Folder properties to be imported using a job or stage level options  statement

### ISSUE THREAD

**Issue by macg33zr** [mig82/folder-properties-plugin#3]
I wanted to import the properties for the whole job or stage.

With pipeline block-scoped steps you can normally use the step at the options section like this:

```
options {
  withFolderProperties()
}
```

But this did not work for me and I get a syntax error. I think it is down to the way the plugin is implemented. If it is a small change, it might be very useful for some users. Nice plugin BTW!

**Comment by mig82** [comment]
Hi Bill, thank you for using my plugin. I'm glad you found it useful. Can
you please mention another plugin that works like this and provide a sample
code snippet for it? I'd like to look at the implementation and see if it's
a quick fix.

**Comment by macg33zr** [comment]
Hi -

The retry step in the basic steps plugin is  an example:
https://github.com/jenkinsci/workflow-basic-steps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStep.java

In the step descriptor, it has this declaration which makes it a block-scoped step and it is then available in options:
```
        @Override
        public boolean takesImplicitBlockArgument() {
            return true;
        }
```

I think the withFolderProperties step in your plugin is declared in a different way, so this is not making it available in the options section.

**Comment by mig82** [comment]
Thank you, @macg33zr . Will definitely look into it as soon as I have some time to spare.

**Comment by kalebwalton** [comment]
Yes, this!

**Comment by szymon3** [comment]
Any progress on this? Thanks

**Comment by mig82** [comment]
Hi @macg33zr . I'm not used to declarative pipeline. I usually rely on scripted pipeline. However, I just tried this and it worked fine.
```
pipeline {
    agent any
    options {
        withFolderProperties()
    }
    stages {
	    stage('Test') {
	        steps {
	            echo("Foo: ${env.FOO}")
	        }
	    }
	}
}
```
Where `FOO` is a property declared in a parent folder. I didn't see any syntax issues and it printed out the folder property's value as expected.

@kalebwalton , @szymon3, I'm closing this. If any of you face it again, please post a sample pipeline I can use to reproduce it. Please do so in the repository under the Jenkinsci org, here:
https://github.com/jenkinsci/folder-properties-plugin
