### ISSUE TITLE
How to set Folder properties in Groovy script?

### ISSUE THREAD

**Issue by vidolch** [mig82/folder-properties-plugin#4]
I am developing a script which creates a folder with sub-projects that should contain predefined set of properties. I cannot wrap my head around how to do this and never saw it documented...

**Comment by mig82** [comment]
Hi @vidolch. I believe you're referring to Job DSL. Then this is how:
```
folder('my folder') {
    properties {
        folderProperties {
            properties {
                stringProperty {
                    key('FOO')
                    value('foo1')
                }
            }
        }
    }
}
```
It's documented here:
https://plugins.jenkins.io/folder-properties/#FolderPropertiesPlugin-JobDSL
