### ISSUE TITLE
Access properties in ActiveChoiceParameter 

### ISSUE THREAD

**Issue by cristianrat** [mig82/folder-properties-plugin#5]
Long story short, a pipeline has an ActiveChoice parameter which is populated via an API call (before the pipeline is built).
I'd like the pass some params for that API call which are set at folder level with this plugin.
How could I access those?
For example, cloudbees has this example with a different plugin: https://support.cloudbees.com/hc/en-us/articles/360015623532-How-to-use-Folder-Vars-with-Active-Choices-Groovy-script

We appreciate your plugin, we use it quite a lot!

**Comment by mig82** [comment]
Hi. Thank you for using my plugin :)
Judging by the example you've pointed out, I think you could try something like this.
```
def p = Jenkins.instance.getItemByFullName("FOLDER-A/job-B")
    .getParent()
    .getProperties()
    .getAll(com.mig82.folders.properties.FolderProperties.class).get(0)
```
I'm not able to test this now. Give it a go and let me know if it works.

**Comment by cristianrat** [comment]
Hi,

In the meantime I found a different way via job name, but would like to know how to access params differently
I tried your above and the return is `com.mig82.folders.properties.FolderProperties@42ffb8c8`

If I go further and try `def myvar = p.getClass().getDeclaredField("properties").get(p)`
(I assume properties exists or if not, not sure what it should be) 
Result is `Class java_lang_reflect_Field$get can not access a member of class com.mig82.folders.properties.FolderProperties with modifiers "private final"`

**Comment by mig82** [comment]
If you're getting `com.mig82.folders.properties.FolderProperties@42ffb8c8` that sounds good. You just need to then invoke `getProperties` on that. See its definition [here](https://github.com/jenkinsci/folder-properties-plugin/blob/c635fb61f4dc6499ec95148fdbdc9172c2a28615/src/main/java/com/mig82/folders/properties/FolderProperties.java#L58).

**Comment by cristianrat** [comment]
Brilliant, that's it. It works :) 
For anyone looking at this issue, it's like @mig82 said and then just p.getProperties() will get you an array of properties which you can get what you need from
Thanks again!

**Comment by mig82** [comment]
No problem. Happy to help.
